name: Run Python Script

on:
  schedule:
    - cron: '59 22 * * *' 
  workflow_dispatch:


jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Run Python script
      env:
        SECRET_VAR: ${{ secrets.MY_SECRET_VAR }} 
         # 替换成你的 secret 变量名称
      run: 
        pip install requests
        python test.py
